apiVersion: v2
name: ceph-operations
description: Ceph operations bundle
type: application
version: 1.8.21
maintainers:
  - name: sumitarora2786
  - name: richardtief
  - name: ibakshay
dependencies:
  - name: owner-info
    repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
    version: 1.0.0